application/music-player/app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class User(UserMixin, db.Model):
    
    __tablename__ = 'users'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True, nullable=False)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    albums = db.relationship('Album', backref='user', lazy='dynamic')

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Album(db.Model):

    __tablename__ = 'albums'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True, nullable=False)
    name = db.Column(db.String(60), nullable=False)    
    picturelink = db.Column(db.String(300), nullable=False)
    songs = db.relationship('Song', backref='album', lazy='dynamic')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return '<Album: {}>'.format(self.name)


class Song(db.Model):
   
    __tablename__ = 'songs'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True, nullable=False)
    name = db.Column(db.String(60), nullable=False)
    link = db.Column(db.String(300), nullable=False)
    album_id = db.Column(db.Integer, db.ForeignKey('albums.id'), nullable=False)

    def __repr__(self):
        return '<Song: {}>'.format(self.name)

application/music-player/app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class AlbumForm(FlaskForm):    
    name = StringField('Name', validators=[DataRequired()])
    picturelink = StringField('Picture url', validators=[DataRequired()])
    submit = SubmitField('Add Album')
    
class SongForm(FlaskForm):    
    name = StringField('Name', validators=[DataRequired()])
    link = StringField('Embeded link, like https://www.youtube.com/embed/GY9kQcWLvEM ', validators=[DataRequired()])
    submit = SubmitField('Add Song')

application/music-player/app/__init__.py
# app/__init__.py

# third-party imports
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask import render_template

# local imports
from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')

    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"
    migrate = Migrate(app, db)

    from app import models

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)
    
    @app.errorhandler(403)
    def forbidden(error):
        return render_template('errors/403.html', title='Forbidden'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html', title='Page Not Found'), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template('errors/500.html', title='Server Error'), 500


    return app

application/music-player/app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

application/music-player/app/home/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import home
from forms import AlbumForm, SongForm
from .. import db
from ..models import Album, Song, User

@home.route('/')
def homepage():
    return render_template('/index.html', title="Welcome")

@home.route('/albums', methods=['GET', 'POST'])
@login_required
def albums():
    
    albums = Album.query.filter_by(user_id = current_user.id).all()
    return render_template('/home/albums.html',
                           albums=albums, title="All Albums")


@home.route('/albumdetails/<int:album_id>')
@login_required
def albumdetails(album_id):
    album = Album.query.get_or_404(album_id)
    songs = Song.query.filter_by(album_id=album_id).all()
    return render_template('/home/albumdetails.html', album=album, songs=songs, title="Album Details")


@home.route('/createalbum', methods=['GET', 'POST'])
@login_required
def createalbum():
    user = User.query.get(current_user.id)
    form = AlbumForm()
    if form.validate_on_submit():
        album = Album(name=form.name.data,
                        picturelink=form.picturelink.data,
                        user_id=user.id, 
                        songs=[])
        
        user.albums.append(album)
        db.session.add(album) 
        db.session.commit()

        return redirect('albums')

    return render_template('/home/createalbum.html', action="Add",
                            form=form, title="Add album")

@home.route('/deletealbum/<int:album_id>', methods=['GET', 'POST'])
@login_required
def delete_album(album_id):
    songs = Song.query.filter_by(album_id=album_id).all()
    for s in songs:
        db.session.delete(s)
        db.session.commit()
        
    album = Album.query.get(album_id)
    db.session.delete(album)
    db.session.commit()

    return redirect('/albums')

@home.route('/song/<int:song_id>')
@login_required
def song(song_id):
    song = Song.query.get(song_id)
    return render_template('/home/song.html', song=song, title="Song")
    
@home.route('/home/createsong/<int:album_id>', methods=['GET', 'POST'])
@login_required
def createsong(album_id):
    album = Album.query.get(album_id)
    form = SongForm()
    if form.validate_on_submit():
        song = Song(name=form.name.data,
                        link=form.link.data,
                        album_id=album.id)
        
        album.songs.append(song)
        db.session.add(song) 
        db.session.commit()

        return redirect('/albums')

    return render_template('/home/createsong.html', action="Add",
                           form=form, title="Add song")


@home.route('/deletesong/<int:song_id>', methods=['GET', 'POST'])
@login_required
def delete_song(song_id):
    song = Song.query.get_or_404(song_id)
    db.session.delete(song)
    db.session.commit()

    return redirect('/albums')

application/music-player/app/templates/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <title>{{ title }} | Music Player</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body class="container-fluid">
    <div>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-info">
                <a class="navbar-brand" href="{{ url_for('home.homepage') }}">Music Player</a>
                <span class="navbar-toggler-icon></span>
                <div class="collapse navbar-collapse" id="navbarNav">
				    {% if current_user.is_authenticated %}
						<ul class="navbar-nav">
							<li class="nav-item active">
								<a class="nav-link" href="{{ url_for('home.albums') }}">Albums</a>
							</li>
							<li class="nav-item active">
								<a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
							</li>							
						</ul>
					{% else %}
					    <ul class="navbar-nav">
							<li class="nav-item active">
								<a class="nav-link" href="/">Home</a>
							</li>
							<li class="nav-item active">
								<a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
							</li>
							<li class="nav-item active">
								<a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
							</li>
						</ul>
					{% endif %}
                </div>
            </nav>
        </header>
        <hr class="bg-info" style="height: 2px" />
		<main>

			{% block body %}
			{% endblock %}

		</main>
        <hr class="bg-info" style="height: 2px" />
        <footer class="bg-white">
            <h5 class="font-weight-bold text-center">CopyRight &copy; All rights reserved.</h5>
        </footer>
    </div>
</body>
</html>

application/music-player/app/templates/home/albumdetails.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}

<div class="album-details d-flex justify-content-between row">
    <div class="album-data col-md-5">
        <img src="{{album.picturelink}}" class="img-thumbnail" />
        <h1 class="text-center">Album name: {{album.name}}</h1>
        <div class="d-flex justify-content-between">
            <a href="/home/createsong/{{album.id}}" class="btn bg-info text-white">
                Create Song
            </a>
            <a href="{{ url_for('home.albums') }}" class="btn bg-info text-white">Back To Albums</a>
        </div>
    </div>
    <div class="album-tracks col-md-5">
        <h1>Songs</h1>
	{% if  not songs %}
	   <h6>Currently there are no created songs in this album.</h6>
	{% else %}
    <ol>
        {% for song in songs %}
        <li><a href="/song/{{song.id}}"><h6>{{song.name}}</h6></a></li>
        {% endfor %}
    </ol>
	{% endif %}
    </div>
</div>

{% endblock %}

application/music-player/app/templates/home/albums.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}All Albums{% endblock %}
{% block body %}

<h2 class="text-info">All Albums</h2>
<hr class="bg-info" style="height: 2px" />
<a href="{{ url_for('home.createalbum') }}" class="btn bg-info text-white"><h6>Create Album</h6></a>
<hr class="bg-info" style="height: 2px" />

<div>
	{% if  not albums %}
       <div class-"center">
	   <h6 class="text-center">Currently there are no created albums in your directory.</h6>
	   </div>
	{% else %}	
	<div class="row text-center">
    {% for album in albums %}
	
            <div class="col-lg-3 col-md-6 hero-feature">
                <div class="thumbnail">
                    <img  class="width: 180px; height: 286px;" src="{{album.picturelink}}" alt="">
                    <div class="caption">
                        <h3>{{album.name}}</h3>                        
                        <p class="d-flex justify-content-around">
						    <a href="/albumdetails/{{album.id}}" class="btn btn-info">Details</a>
						    <a href="/deletealbum/{{album.id}}" class="btn btn-danger">Delete</a>
						</p>
                    </div>
                </div>
            </div>

	{% endfor %}
	</div>

	{% endif %}

{% endblock %}

application/music-player/app/templates/home/createalbum.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block body %}
<div class="content-section">
  <div class="center">
    <h1 class="text-center bg-white text-info">Create Album</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

application/music-player/app/templates/home/createsong.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block body %}
<div class="content-section">
  <div class="center">
    <h1 class="text-center bg-white text-info">Create Song</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

application/music-player/app/templates/home/song.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="Song-details">
    <h4 class="text-center">Song Name: {{song.name}}</h4>
    <hr class="bg-info w-50" style="height: 2px" />
    <div class="d-flex justify-content-center">
        <iframe src="{{song.link}}" class="w-50" height="380"></iframe>
    </div>
    <hr class="bg-info w-50" style="height: 2px" />
</div>
<hr class="bg-info w-50" style="height: 2px" />
<div class="d-flex justify-content-around">
    <a class="btn bg-info text-white mt-4" href="/albums">Back To Albums</a>
    <a class="btn bg-info text-white mt-4" href="/deletesong/{{song.id}}">Delete the song</a>
</div>
{% endblock %}

application/music-player/app/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="jumbotron bg-info text-white">
    {% if current_user.is_authenticated %}
        <h1>Welcome, <span class="text-danger"> {{ current_user.username }}</span>!</h1>
        <hr class="bg-white" style="height: 2px" />
        <h2>Music Player wishes you a fun experience.</h2>
	{% else %}
		<h1>Welcome to Music Player!</h1>
		<hr class="bg-white" style="height: 2px" />
		<h2><a class="text-danger" href="{{ url_for('auth.login') }}">Login</a> if you have an account.</h2>
		<h2><a class="text-danger" href="{{ url_for('auth.register') }}">Register</a> if you don't.</h2>
	{% endif %}

</div>
{% endblock %}